# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(442, 392)
        Login.setStyleSheet("background-color: rgb(3, 10, 19);")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(0, 0, 441, 391))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_login = QtWidgets.QPushButton(self.frame)
        self.btn_login.setGeometry(QtCore.QRect(90, 320, 261, 41))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setStyleSheet("font: 11pt \"JetBrains Mono\";\n"
"background-color: rgb(0, 0, 0, 0.4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.btn_login.setObjectName("btn_login")
        self.input_senha = QtWidgets.QLineEdit(self.frame)
        self.input_senha.setGeometry(QtCore.QRect(90, 250, 261, 41))
        self.input_senha.setStyleSheet("font: 9pt \"JetBrains Mono\";\n"
"letter-spacing: 2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.input_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha.setDragEnabled(False)
        self.input_senha.setObjectName("input_senha")
        self.input_usuario = QtWidgets.QLineEdit(self.frame)
        self.input_usuario.setGeometry(QtCore.QRect(90, 180, 261, 41))
        self.input_usuario.setStyleSheet("font: 9pt \"JetBrains Mono\";\n"
"letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.input_usuario.setObjectName("input_usuario")
        self.txt_senha = QtWidgets.QLabel(self.frame)
        self.txt_senha.setGeometry(QtCore.QRect(100, 230, 55, 16))
        self.txt_senha.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_senha.setObjectName("txt_senha")
        self.txt_usuario = QtWidgets.QLabel(self.frame)
        self.txt_usuario.setGeometry(QtCore.QRect(100, 160, 55, 16))
        self.txt_usuario.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_usuario.setObjectName("txt_usuario")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(110, 0, 211, 161))
        self.logo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("designer\\../img/icon.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Sistema de Login"))
        self.btn_login.setText(_translate("Login", "Login"))
        self.txt_senha.setText(_translate("Login", "Senha:"))
        self.txt_usuario.setText(_translate("Login", "CPF:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon("img/icon.png"))
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
