# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/login-copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(459, 419)
        Login.setStyleSheet("background-color: rgb(3, 10, 19);")
        icon = QtGui.QIcon("img/icon.png")
        Login.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setMinimumSize(QtCore.QSize(441, 391))
        self.frame.setMaximumSize(QtCore.QSize(441, 391))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_usuario = QtWidgets.QLabel(self.frame)
        self.txt_usuario.setMinimumSize(QtCore.QSize(55, 16))
        self.txt_usuario.setMaximumSize(QtCore.QSize(55, 16))
        self.txt_usuario.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_usuario.setObjectName("txt_usuario")
        self.gridLayout.addWidget(self.txt_usuario, 1, 0, 1, 1)
        self.txt_senha = QtWidgets.QLabel(self.frame)
        self.txt_senha.setMinimumSize(QtCore.QSize(55, 16))
        self.txt_senha.setMaximumSize(QtCore.QSize(55, 16))
        self.txt_senha.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_senha.setObjectName("txt_senha")
        self.gridLayout.addWidget(self.txt_senha, 3, 0, 1, 1)
        self.input_usuario = QtWidgets.QLineEdit(self.frame)
        self.input_usuario.setMinimumSize(QtCore.QSize(261, 41))
        self.input_usuario.setMaximumSize(QtCore.QSize(261, 41))
        self.input_usuario.setStyleSheet("font: 9pt \"JetBrains Mono\";\n"
"letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.input_usuario.setObjectName("input_usuario")
        self.gridLayout.addWidget(self.input_usuario, 2, 0, 1, 1)
        self.input_senha = QtWidgets.QLineEdit(self.frame)
        self.input_senha.setMinimumSize(QtCore.QSize(261, 41))
        self.input_senha.setMaximumSize(QtCore.QSize(261, 41))
        self.input_senha.setStyleSheet("font: 9pt \"JetBrains Mono\";\n"
"letter-spacing: 2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.input_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha.setDragEnabled(False)
        self.input_senha.setObjectName("input_senha")
        self.gridLayout.addWidget(self.input_senha, 5, 0, 1, 1)
        self.btn_login = QtWidgets.QPushButton(self.frame)
        self.btn_login.setMinimumSize(QtCore.QSize(261, 41))
        self.btn_login.setMaximumSize(QtCore.QSize(261, 41))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setStyleSheet("font: 11pt \"JetBrains Mono\";\n"
"background-color: rgb(0, 0, 0, 0.4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 8, 0, 1, 1)
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setMinimumSize(QtCore.QSize(261, 186))
        self.logo.setMaximumSize(QtCore.QSize(261, 186))
        self.logo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("designer\\../img/icon.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 0, 0, 1, 1)
        self.visual = QtWidgets.QLabel(self.frame)
        self.visual.setMinimumSize(QtCore.QSize(55, 16))
        self.visual.setMaximumSize(QtCore.QSize(55, 16))
        self.visual.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.visual.setText("")
        self.visual.setObjectName("visual")
        self.gridLayout.addWidget(self.visual, 7, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login do Sistema de Agendamento"))
        self.txt_usuario.setText(_translate("Login", "CPF:"))
        self.txt_senha.setText(_translate("Login", "Senha:"))
        self.btn_login.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
