# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainAdmin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(3, 10, 19);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cadastra_data = QtWidgets.QFrame(self.centralwidget)
        self.cadastra_data.setGeometry(QtCore.QRect(0, 320, 411, 281))
        self.cadastra_data.setStyleSheet("background-color: rgb(3, 10, 19);")
        self.cadastra_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cadastra_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cadastra_data.setObjectName("cadastra_data")
        self.nome = QtWidgets.QLineEdit(self.cadastra_data)
        self.nome.setGeometry(QtCore.QRect(10, 50, 221, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.nome.setFont(font)
        self.nome.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.nome.setObjectName("nome")
        self.confirmar_data = QtWidgets.QPushButton(self.cadastra_data)
        self.confirmar_data.setGeometry(QtCore.QRect(250, 230, 151, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.confirmar_data.setFont(font)
        self.confirmar_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmar_data.setStyleSheet("background-color: rgb(0, 0, 0, 0.4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.confirmar_data.setObjectName("confirmar_data")
        self.hora_inicio = QtWidgets.QTimeEdit(self.cadastra_data)
        self.hora_inicio.setGeometry(QtCore.QRect(250, 110, 151, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.hora_inicio.setFont(font)
        self.hora_inicio.setStyleSheet("QTimeEdit {\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 7px;\n"
"    letter-spacing: 1.2px;\n"
"}\n"
"\n"
"QTimeEdit::up-button {\n"
"    image: url(img/stat.png);\n"
"}\n"
"\n"
"QTimeEdit::down-button {\n"
"    image: url(img/stat_minus.png);\n"
"}")
        self.hora_inicio.setObjectName("hora_inicio")
        self.cpf = QtWidgets.QLineEdit(self.cadastra_data)
        self.cpf.setGeometry(QtCore.QRect(10, 110, 221, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.cpf.setFont(font)
        self.cpf.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.cpf.setObjectName("cpf")
        self.contato = QtWidgets.QLineEdit(self.cadastra_data)
        self.contato.setGeometry(QtCore.QRect(10, 230, 221, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.contato.setFont(font)
        self.contato.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.contato.setObjectName("contato")
        self.hora_termino = QtWidgets.QTimeEdit(self.cadastra_data)
        self.hora_termino.setGeometry(QtCore.QRect(250, 170, 151, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.hora_termino.setFont(font)
        self.hora_termino.setStyleSheet("QTimeEdit {\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 7px;\n"
"    letter-spacing: 1.2px;\n"
"}\n"
"\n"
"QTimeEdit::up-button {\n"
"    image: url(img/stat.png);\n"
"}\n"
"\n"
"QTimeEdit::down-button {\n"
"    image: url(img/stat_minus.png);\n"
"}")
        self.hora_termino.setTimeSpec(QtCore.Qt.LocalTime)
        self.hora_termino.setObjectName("hora_termino")
        self.num_consultorio = QtWidgets.QLineEdit(self.cadastra_data)
        self.num_consultorio.setGeometry(QtCore.QRect(10, 170, 221, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.num_consultorio.setFont(font)
        self.num_consultorio.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.num_consultorio.setObjectName("num_consultorio")
        self.txt_nome = QtWidgets.QLabel(self.cadastra_data)
        self.txt_nome.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.txt_nome.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_nome.setObjectName("txt_nome")
        self.txt_cpf = QtWidgets.QLabel(self.cadastra_data)
        self.txt_cpf.setGeometry(QtCore.QRect(20, 90, 55, 16))
        self.txt_cpf.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_cpf.setObjectName("txt_cpf")
        self.txt_num_consultorio = QtWidgets.QLabel(self.cadastra_data)
        self.txt_num_consultorio.setGeometry(QtCore.QRect(20, 150, 161, 16))
        self.txt_num_consultorio.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_num_consultorio.setObjectName("txt_num_consultorio")
        self.txt_contato = QtWidgets.QLabel(self.cadastra_data)
        self.txt_contato.setGeometry(QtCore.QRect(20, 210, 201, 16))
        self.txt_contato.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_contato.setObjectName("txt_contato")
        self.txt_hora_inicio = QtWidgets.QLabel(self.cadastra_data)
        self.txt_hora_inicio.setGeometry(QtCore.QRect(270, 90, 111, 16))
        self.txt_hora_inicio.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_hora_inicio.setObjectName("txt_hora_inicio")
        self.txt_hora_final = QtWidgets.QLabel(self.cadastra_data)
        self.txt_hora_final.setGeometry(QtCore.QRect(270, 150, 111, 16))
        self.txt_hora_final.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_hora_final.setObjectName("txt_hora_final")
        self.date = QtWidgets.QDateEdit(self.cadastra_data)
        self.date.setGeometry(QtCore.QRect(260, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.date.setFont(font)
        self.date.setStyleSheet("QDateEdit {\n"
"    letter-spacing: 1.2px;\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 15px;\n"
"}\n"
"\n"
"QDateEdit::up-button {\n"
"    image: none;\n"
"    width: 0;\n"
"    padding: -1000px\n"
"}\n"
"\n"
"QDateEdit::down-button {\n"
"    image: none;\n"
"    width: 0;\n"
"    padding: -1000px\n"
"}\n"
"")
        self.date.setObjectName("date")
        self.txt_data = QtWidgets.QLabel(self.cadastra_data)
        self.txt_data.setGeometry(QtCore.QRect(300, 30, 31, 16))
        self.txt_data.setStyleSheet("font: 8pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_data.setObjectName("txt_data")
        self.sistema_data = QtWidgets.QLabel(self.cadastra_data)
        self.sistema_data.setGeometry(QtCore.QRect(120, 0, 171, 21))
        self.sistema_data.setStyleSheet("font: 11pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.sistema_data.setObjectName("sistema_data")
        self.tela_btn = QtWidgets.QFrame(self.centralwidget)
        self.tela_btn.setGeometry(QtCore.QRect(419, -1, 381, 31))
        self.tela_btn.setStyleSheet("background-color: rgb(2, 13, 27);")
        self.tela_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_btn.setObjectName("tela_btn")
        self.btn_agendamentos = QtWidgets.QPushButton(self.tela_btn)
        self.btn_agendamentos.setGeometry(QtCore.QRect(10, 5, 171, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_agendamentos.sizePolicy().hasHeightForWidth())
        self.btn_agendamentos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.btn_agendamentos.setFont(font)
        self.btn_agendamentos.setStyleSheet("background-color: rgb(0, 0, 0, 0.4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.btn_agendamentos.setObjectName("btn_agendamentos")
        self.btn_cadastro_users = QtWidgets.QPushButton(self.tela_btn)
        self.btn_cadastro_users.setGeometry(QtCore.QRect(200, 5, 171, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cadastro_users.sizePolicy().hasHeightForWidth())
        self.btn_cadastro_users.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.btn_cadastro_users.setFont(font)
        self.btn_cadastro_users.setStyleSheet("background-color: rgb(0, 0, 0, 0.4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.btn_cadastro_users.setObjectName("btn_cadastro_users")
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setEnabled(True)
        self.pages.setGeometry(QtCore.QRect(420, 30, 381, 571))
        self.pages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pages.setStyleSheet("background-color: rgb(3, 10, 19);")
        self.pages.setObjectName("pages")
        self.pg_agendamentos = QtWidgets.QWidget()
        self.pg_agendamentos.setObjectName("pg_agendamentos")
        self.Data_sel = QtWidgets.QLabel(self.pg_agendamentos)
        self.Data_sel.setGeometry(QtCore.QRect(0, 0, 221, 31))
        self.Data_sel.setStyleSheet("font: 12pt \"JetBrains Mono\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.Data_sel.setObjectName("Data_sel")
        self.pages.addWidget(self.pg_agendamentos)
        self.pg_cadastro_users = QtWidgets.QWidget()
        self.pg_cadastro_users.setObjectName("pg_cadastro_users")
        self.c_titulo = QtWidgets.QLabel(self.pg_cadastro_users)
        self.c_titulo.setGeometry(QtCore.QRect(90, 10, 201, 61))
        self.c_titulo.setStyleSheet("font: 13pt \"JetBrains Mono\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.c_titulo.setObjectName("c_titulo")
        self.c_nome = QtWidgets.QLineEdit(self.pg_cadastro_users)
        self.c_nome.setGeometry(QtCore.QRect(20, 130, 341, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.c_nome.setFont(font)
        self.c_nome.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.c_nome.setObjectName("c_nome")
        self.c_cpf = QtWidgets.QLineEdit(self.pg_cadastro_users)
        self.c_cpf.setGeometry(QtCore.QRect(20, 210, 341, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.c_cpf.setFont(font)
        self.c_cpf.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.c_cpf.setObjectName("c_cpf")
        self.c_senha = QtWidgets.QLineEdit(self.pg_cadastro_users)
        self.c_senha.setGeometry(QtCore.QRect(20, 290, 341, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.c_senha.setFont(font)
        self.c_senha.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.c_senha.setObjectName("c_senha")
        self.c_senha_confirmar = QtWidgets.QLineEdit(self.pg_cadastro_users)
        self.c_senha_confirmar.setGeometry(QtCore.QRect(20, 370, 341, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.c_senha_confirmar.setFont(font)
        self.c_senha_confirmar.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.c_senha_confirmar.setObjectName("c_senha_confirmar")
        self.confirmar_cadastro = QtWidgets.QPushButton(self.pg_cadastro_users)
        self.confirmar_cadastro.setGeometry(QtCore.QRect(20, 520, 341, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.confirmar_cadastro.setFont(font)
        self.confirmar_cadastro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmar_cadastro.setStyleSheet("background-color: rgb(0, 0, 0, 0.4);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.confirmar_cadastro.setObjectName("confirmar_cadastro")
        self.check_admin = QtWidgets.QCheckBox(self.pg_cadastro_users)
        self.check_admin.setGeometry(QtCore.QRect(70, 470, 241, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.check_admin.setFont(font)
        self.check_admin.setStyleSheet("QCheckBox {\n"
"    letter-spacing: 1.2px;\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 15px\n"
" }\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    image: url(img/checkbox_unchecked.ico);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    width: 18px;\n"
"    height: 180px;\n"
"    image: url(img/checkbox_indeterminate.ico);\n"
"}")
        self.check_admin.setObjectName("check_admin")
        self.check_normal = QtWidgets.QCheckBox(self.pg_cadastro_users)
        self.check_normal.setGeometry(QtCore.QRect(80, 420, 221, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.check_normal.setFont(font)
        self.check_normal.setStyleSheet("QCheckBox {\n"
"    letter-spacing: 1.2px;\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 15px\n"
" }\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    image: url(img/checkbox_unchecked.ico);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    width: 18px;\n"
"    height: 180px;\n"
"    image: url(img/checkbox_indeterminate.ico);\n"
"}")
        self.check_normal.setObjectName("check_normal")
        self.text_c_nome = QtWidgets.QLabel(self.pg_cadastro_users)
        self.text_c_nome.setGeometry(QtCore.QRect(30, 100, 171, 21))
        self.text_c_nome.setStyleSheet("font: 12pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_c_nome.setObjectName("text_c_nome")
        self.text_c_nome_2 = QtWidgets.QLabel(self.pg_cadastro_users)
        self.text_c_nome_2.setGeometry(QtCore.QRect(30, 190, 171, 21))
        self.text_c_nome_2.setStyleSheet("font: 12pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_c_nome_2.setObjectName("text_c_nome_2")
        self.text_c_nome_3 = QtWidgets.QLabel(self.pg_cadastro_users)
        self.text_c_nome_3.setGeometry(QtCore.QRect(30, 260, 171, 21))
        self.text_c_nome_3.setStyleSheet("font: 12pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_c_nome_3.setObjectName("text_c_nome_3")
        self.text_c_nome_4 = QtWidgets.QLabel(self.pg_cadastro_users)
        self.text_c_nome_4.setGeometry(QtCore.QRect(30, 340, 171, 21))
        self.text_c_nome_4.setStyleSheet("font: 12pt \"JetBrains Mono\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.text_c_nome_4.setObjectName("text_c_nome_4")
        self.pages.addWidget(self.pg_cadastro_users)
        self.calendario = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendario.setGeometry(QtCore.QRect(0, 0, 419, 311))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.calendario.setFont(font)
        self.calendario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calendario.setStyleSheet("/* Definição de cor para vários elementos dentro do QCalendarWidget */\n"
"QCalendarWidget QSpinBox#qt_calendar_yearedit,\n"
"QCalendarWidget QSpinBox#qt_calendar_monthedit,\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton,\n"
"QCalendarWidget QToolButton#qt_calendar_yearbutton,\n"
"QCalendarWidget QTableView#qt_calendar_calendarview,\n"
"QCalendarWidget QMenu, \n"
"#calendarWidget QToolButton QMenu {\n"
"    color: rgb(255, 255, 255);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Definição de cor para a janela de seleção de mês */\n"
"QCalendarWidget QMenu {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Definição de cores e estilos para a barra de navegação e visualização do calendário */\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar,\n"
"#qt_calendar_calendarview {\n"
"    background-color: rgb(3, 10, 19);\n"
"    alternate-background-color: rgba(0, 18, 40, 0.37);\n"
"    selection-background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Definição de estilos para os botões de navegação do calendário */\n"
"QCalendarWidget QWidget#qt_calendar_prevmonth,\n"
"QCalendarWidget QWidget#qt_calendar_nextmonth {\n"
"    border: none;\n"
"    qproperty-icon: none;\n"
"    min-height: 13px;\n"
"    min-width: 13px;\n"
"    max-height: 13px;\n"
"    max-width: 13px;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Definição de ícones para os botões de navegação do calendário */\n"
"QCalendarWidget QWidget#qt_calendar_prevmonth {\n"
"    margin-left: 5px;\n"
"    image: url(img/chevron_left.png);\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_nextmonth {\n"
"    margin-right: 5px;\n"
"    image: url(img/chevron_right.png);\n"
"}\n"
"\n"
"/* Estilização dos botões de navegação quando pressionados */\n"
"QCalendarWidget QWidget#qt_calendar_prevmonth:pressed,\n"
"QCalendarWidget QWidget#qt_calendar_nextmonth:pressed {\n"
"    background-color: rgb(0, 18, 40);\n"
"}\n"
"\n"
"/* Estilização dos botões de mês e ano quando o mouse passa sobre eles */\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton:hover,\n"
"QCalendarWidget QToolButton#qt_calendar_yeamutton:hover {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização dos botões de mês e ano quando pressionados */\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton:pressed,\n"
"QCalendarWidget QToolButton#qt_calendar_yeamutton:pressed {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização dos botões de ano */\n"
"QCalendarWidget QToolButton#qt_calendar_yearbutton {\n"
"    margin: 5px;\n"
"    border-radius: 5px;\n"
"    padding: 0 10px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Estilização dos botões de mês */\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton {\n"
"    margin: 5px 0;\n"
"    border-radius: 5px;\n"
"    padding: 0px 2px;\n"
"    font-size: 13px;\n"
"    width: 90px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Estilização do campo de edição do ano */\n"
"#qt_calendar_yearedit {\n"
"    min-width: 53px;\n"
"    background: transparent;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Definição de ícones e estilos para os botões de aumento e diminuição do ano */\n"
"#qt_calendar_yearedit::down-button {\n"
"    subcontrol-position: left;\n"
"    image: url(img/stat_minus.png);\n"
"}\n"
"\n"
"#qt_calendar_yearedit::up-button {\n"
"    subcontrol-position: right;\n"
"    image: url(img/stat.png);\n"
"}\n"
"\n"
"#qt_calendar_yearedit::up-button,\n"
"#qt_calendar_yearedit::down-button {\n"
"    width: 10px;\n"
"    padding: 0px 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Estilização dos botões de aumento e diminuição do ano quando o mouse passa sobre eles */\n"
"#qt_calendar_yearedit::up-button:hover,\n"
"#qt_calendar_yearedit::down-button:hover {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização dos botões de aumento e diminuição do ano quando pressionados */\n"
"#qt_calendar_yearedit::up-button:pressed,\n"
"#qt_calendar_yearedit::down-button:pressed {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização do menu suspenso dentro do QCalendarWidget */\n"
"#calendarWidget QToolButton QMenu {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização da visualização do calendário */\n"
"#qt_calendar_calendarview {\n"
"    border: 5px solid rgb(2, 13, 27);\n"
"    border-top: 0px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"")
        self.calendario.setObjectName("calendario")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.confirmar_data.setText(_translate("MainWindow", "Confirmar"))
        self.txt_nome.setText(_translate("MainWindow", "Nome:"))
        self.txt_cpf.setText(_translate("MainWindow", "CPF:"))
        self.txt_num_consultorio.setText(_translate("MainWindow", "Número do consultorio:"))
        self.txt_contato.setText(_translate("MainWindow", "Número do Celular ou E-mail:"))
        self.txt_hora_inicio.setText(_translate("MainWindow", "Hora de inicio:"))
        self.txt_hora_final.setText(_translate("MainWindow", "Hora de termino:"))
        self.txt_data.setText(_translate("MainWindow", "Data"))
        self.sistema_data.setText(_translate("MainWindow", "Cadastrar Consulta:"))
        self.btn_agendamentos.setText(_translate("MainWindow", "Agendamento"))
        self.btn_cadastro_users.setText(_translate("MainWindow", "Cadastro de Usuarío"))
        self.Data_sel.setText(_translate("MainWindow", "Data Selecionada:"))
        self.c_titulo.setText(_translate("MainWindow", "Cadastro de Usuarío:"))
        self.confirmar_cadastro.setText(_translate("MainWindow", "Confirmar"))
        self.check_admin.setText(_translate("MainWindow", "O Usuário é Funcionário"))
        self.check_normal.setText(_translate("MainWindow", "O Usuarío é Paciente"))
        self.text_c_nome.setText(_translate("MainWindow", "Nome:"))
        self.text_c_nome_2.setText(_translate("MainWindow", "CPF:"))
        self.text_c_nome_3.setText(_translate("MainWindow", "Senha:"))
        self.text_c_nome_4.setText(_translate("MainWindow", "Confirmar Senha:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon("img/icon.png"))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainAdmin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
