# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main_users.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainUsers(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 599)
        icon = QtGui.QIcon("img/icon.png")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background-color: rgb(2, 13, 27);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_calendario = QtWidgets.QPushButton(self.frame)
        self.btn_calendario.setGeometry(QtCore.QRect(10, 10, 211, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.btn_calendario.setFont(font)
        self.btn_calendario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_calendario.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.btn_calendario.setObjectName("btn_calendario")
        self.btn_consultas = QtWidgets.QPushButton(self.frame)
        self.btn_consultas.setGeometry(QtCore.QRect(270, 10, 231, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.btn_consultas.setFont(font)
        self.btn_consultas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_consultas.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.btn_consultas.setObjectName("btn_consultas")
        self.voltar_login = QtWidgets.QPushButton(self.frame)
        self.voltar_login.setGeometry(QtCore.QRect(760, 10, 31, 23))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.voltar_login.setFont(font)
        self.voltar_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.voltar_login.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(170, 0, 0);\n"
"border-radius:  7px;\n"
"")
        self.voltar_login.setObjectName("voltar_login")
        self.pages_users = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages_users.setGeometry(QtCore.QRect(-1, 39, 801, 561))
        self.pages_users.setObjectName("pages_users")
        self.pg_calendario = QtWidgets.QWidget()
        self.pg_calendario.setObjectName("pg_calendario")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.pg_calendario)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 801, 561))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("/* Definição de cor para vários elementos dentro do QCalendarWidget */\n"
"QCalendarWidget QSpinBox#qt_calendar_yearedit,\n"
"QCalendarWidget QSpinBox#qt_calendar_monthedit,\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton,\n"
"QCalendarWidget QToolButton#qt_calendar_yearbutton,\n"
"QCalendarWidget QTableView#qt_calendar_calendarview,\n"
"QCalendarWidget QMenu, \n"
"#calendarWidget QToolButton QMenu {\n"
"    color: rgb(255, 255, 255);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Definição de cor para a janela de seleção de mês */\n"
"QCalendarWidget QMenu {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Definição de cores e estilos para a barra de navegação e visualização do calendário */\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar,\n"
"#qt_calendar_calendarview {\n"
"    background-color: rgb(3, 10, 19);\n"
"    alternate-background-color: rgba(0, 18, 40, 0.37);\n"
"    selection-background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Definição de estilos para os botões de navegação do calendário */\n"
"QCalendarWidget QWidget#qt_calendar_prevmonth,\n"
"QCalendarWidget QWidget#qt_calendar_nextmonth {\n"
"    border: none;\n"
"    qproperty-icon: none;\n"
"    min-height: 13px;\n"
"    min-width: 13px;\n"
"    max-height: 13px;\n"
"    max-width: 13px;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Definição de ícones para os botões de navegação do calendário */\n"
"QCalendarWidget QWidget#qt_calendar_prevmonth {\n"
"    margin-left: 5px;\n"
"    image: url(img/chevron_left.png);\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_nextmonth {\n"
"    margin-right: 5px;\n"
"    image: url(img/chevron_right.png);\n"
"}\n"
"\n"
"/* Estilização dos botões de navegação quando pressionados */\n"
"QCalendarWidget QWidget#qt_calendar_prevmonth:pressed,\n"
"QCalendarWidget QWidget#qt_calendar_nextmonth:pressed {\n"
"    background-color: rgb(0, 18, 40);\n"
"}\n"
"\n"
"/* Estilização dos botões de mês e ano quando o mouse passa sobre eles */\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton:hover,\n"
"QCalendarWidget QToolButton#qt_calendar_yeamutton:hover {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização dos botões de mês e ano quando pressionados */\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton:pressed,\n"
"QCalendarWidget QToolButton#qt_calendar_yeamutton:pressed {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização dos botões de ano */\n"
"QCalendarWidget QToolButton#qt_calendar_yearbutton {\n"
"    margin: 5px;\n"
"    border-radius: 5px;\n"
"    padding: 0 10px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Estilização dos botões de mês */\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton {\n"
"    margin: 5px 0;\n"
"    border-radius: 5px;\n"
"    padding: 0px 2px;\n"
"    font-size: 13px;\n"
"    width: 90px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Estilização do campo de edição do ano */\n"
"#qt_calendar_yearedit {\n"
"    min-width: 53px;\n"
"    background: transparent;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Definição de ícones e estilos para os botões de aumento e diminuição do ano */\n"
"#qt_calendar_yearedit::down-button {\n"
"    subcontrol-position: left;\n"
"    image: url(img/stat_minus.png);\n"
"}\n"
"\n"
"#qt_calendar_yearedit::up-button {\n"
"    subcontrol-position: right;\n"
"    image: url(img/stat.png);\n"
"}\n"
"\n"
"#qt_calendar_yearedit::up-button,\n"
"#qt_calendar_yearedit::down-button {\n"
"    width: 10px;\n"
"    padding: 0px 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Estilização dos botões de aumento e diminuição do ano quando o mouse passa sobre eles */\n"
"#qt_calendar_yearedit::up-button:hover,\n"
"#qt_calendar_yearedit::down-button:hover {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização dos botões de aumento e diminuição do ano quando pressionados */\n"
"#qt_calendar_yearedit::up-button:pressed,\n"
"#qt_calendar_yearedit::down-button:pressed {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização do menu suspenso dentro do QCalendarWidget */\n"
"#calendarWidget QToolButton QMenu {\n"
"    background-color: rgb(0, 18, 35);\n"
"}\n"
"\n"
"/* Estilização da visualização do calendário */\n"
"#qt_calendar_calendarview {\n"
"    border: 5px solid rgb(2, 13, 27);\n"
"    border-top: 0px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.pages_users.addWidget(self.pg_calendario)
        self.pg_consultas = QtWidgets.QWidget()
        self.pg_consultas.setObjectName("pg_consultas")
        self.frame_2 = QtWidgets.QFrame(self.pg_consultas)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 191, 561))
        self.frame_2.setStyleSheet("background-color: rgb(2, 13, 27);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pesquisar = QtWidgets.QPushButton(self.frame_2)
        self.pesquisar.setGeometry(QtCore.QRect(10, 460, 171, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.pesquisar.setFont(font)
        self.pesquisar.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.pesquisar.setObjectName("pesquisar")
        self.date1 = QtWidgets.QDateEdit(self.frame_2)
        self.date1.setGeometry(QtCore.QRect(40, 50, 111, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.date1.setFont(font)
        self.date1.setStyleSheet("QDateEdit {\n"
"    letter-spacing: 1.2px;\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 15px;\n"
"}\n"
"\n"
"QDateEdit::up-button {\n"
"    image: none;\n"
"    width: 0;\n"
"    padding: -1000px\n"
"}\n"
"\n"
"QDateEdit::down-button {\n"
"    image: none;\n"
"    width: 0;\n"
"    padding: -1000px\n"
"}\n"
"")
        self.date1.setObjectName("date1")
        self.p_consulta = QtWidgets.QLabel(self.frame_2)
        self.p_consulta.setGeometry(QtCore.QRect(0, 100, 191, 31))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.p_consulta.setFont(font)
        self.p_consulta.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;")
        self.p_consulta.setObjectName("p_consulta")
        self.data_sel1 = QtWidgets.QLabel(self.frame_2)
        self.data_sel1.setGeometry(QtCore.QRect(20, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.data_sel1.setFont(font)
        self.data_sel1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"padding: 9px;")
        self.data_sel1.setObjectName("data_sel1")
        self.nome1 = QtWidgets.QLineEdit(self.frame_2)
        self.nome1.setGeometry(QtCore.QRect(10, 170, 171, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.nome1.setFont(font)
        self.nome1.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.nome1.setObjectName("nome1")
        self.contato1 = QtWidgets.QLineEdit(self.frame_2)
        self.contato1.setGeometry(QtCore.QRect(10, 410, 171, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.contato1.setFont(font)
        self.contato1.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.contato1.setObjectName("contato1")
        self.cpf1 = QtWidgets.QLineEdit(self.frame_2)
        self.cpf1.setGeometry(QtCore.QRect(10, 250, 171, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.cpf1.setFont(font)
        self.cpf1.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.cpf1.setObjectName("cpf1")
        self.num_consultorio1 = QtWidgets.QLineEdit(self.frame_2)
        self.num_consultorio1.setGeometry(QtCore.QRect(10, 330, 171, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.num_consultorio1.setFont(font)
        self.num_consultorio1.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.num_consultorio1.setObjectName("num_consultorio1")
        self.check_contato = QtWidgets.QCheckBox(self.frame_2)
        self.check_contato.setGeometry(QtCore.QRect(10, 379, 171, 21))
        self.check_contato.setStyleSheet("QCheckBox {\n"
"    letter-spacing: 1.2px;\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 15px\n"
" }\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    image: url(img/checkbox_unchecked.ico);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    image: url(img/checkbox_indeterminate.ico);\n"
"}")
        self.check_contato.setObjectName("check_contato")
        self.pesquisar_cancelar = QtWidgets.QPushButton(self.frame_2)
        self.pesquisar_cancelar.setGeometry(QtCore.QRect(10, 510, 171, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.pesquisar_cancelar.setFont(font)
        self.pesquisar_cancelar.setStyleSheet("letter-spacing: 1.2px;\n"
"background-color: rgb(0, 18, 40, .37);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:  7px;\n"
"")
        self.pesquisar_cancelar.setObjectName("pesquisar_cancelar")
        self.check_num_consultorio = QtWidgets.QCheckBox(self.frame_2)
        self.check_num_consultorio.setGeometry(QtCore.QRect(10, 300, 171, 21))
        self.check_num_consultorio.setStyleSheet("QCheckBox {\n"
"    letter-spacing: 1.2px;\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 15px\n"
" }\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    image: url(img/checkbox_unchecked.ico);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    image: url(img/checkbox_indeterminate.ico);\n"
"}")
        self.check_num_consultorio.setObjectName("check_num_consultorio")
        self.check_cpf = QtWidgets.QCheckBox(self.frame_2)
        self.check_cpf.setGeometry(QtCore.QRect(10, 220, 171, 21))
        self.check_cpf.setStyleSheet("QCheckBox {\n"
"    letter-spacing: 1.2px;\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 15px\n"
" }\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    image: url(img/checkbox_unchecked.ico);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    image: url(img/checkbox_indeterminate.ico);\n"
"}")
        self.check_cpf.setObjectName("check_cpf")
        self.check_nome = QtWidgets.QCheckBox(self.frame_2)
        self.check_nome.setGeometry(QtCore.QRect(10, 140, 171, 21))
        self.check_nome.setStyleSheet("QCheckBox {\n"
"    letter-spacing: 1.2px;\n"
"    background-color: rgb(0, 18, 40, .37);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:  7px;\n"
"    padding: 15px\n"
" }\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    image: url(img/checkbox_unchecked.ico);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    image: url(img/checkbox_indeterminate.ico);\n"
"}")
        self.check_nome.setObjectName("check_nome")
        self.tableWidget = QtWidgets.QTableWidget(self.pg_consultas)
        self.tableWidget.setGeometry(QtCore.QRect(190, 0, 611, 560))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(3, 10, 19);\n"
"border:none;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.pages_users.addWidget(self.pg_consultas)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages_users.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Agendamento"))
        self.btn_calendario.setText(_translate("MainWindow", "Calendario"))
        self.btn_consultas.setText(_translate("MainWindow", "Consultas"))
        self.voltar_login.setText(_translate("MainWindow", "X"))
        self.pesquisar.setText(_translate("MainWindow", "Pesquisar"))
        self.p_consulta.setText(_translate("MainWindow", "Procurar por Consulta:"))
        self.data_sel1.setText(_translate("MainWindow", "Data Selecionda:"))
        self.check_contato.setText(_translate("MainWindow", "   Número ou E-mail:"))
        self.pesquisar_cancelar.setText(_translate("MainWindow", "Cancelar Pesquisa"))
        self.check_num_consultorio.setText(_translate("MainWindow", "   Consultorio:"))
        self.check_cpf.setText(_translate("MainWindow", "   CPF:"))
        self.check_nome.setText(_translate("MainWindow", "   Nome:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "cpf"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "num_consultorio"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "contato"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainUsers()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
